<?php
error_reporting(E_PARSE);
include_once "../Classes/FileMangerClass.php";
include_once "../Classes/OrderClass.php";
include_once "../Classes/OrderDetailsClass.php";
include_once "../Classes/OutPutClass.php";
include_once "../Classes/PersonClass.php";
include_once "../Classes/ProductClass.php";
include_once "../Classes/TypeClass.php";
include_once "../Classes/UserClass.php";
include_once "../Classes/CashPayment.php";
include_once "../Classes/FawryPayment.php";
include_once "../Classes/VisaPayment.php";
include_once "../../Classes/FileMangerClass.php";
include_once "../../Classes/OrderClass.php";
include_once "../../Classes/OrderDetailsClass.php";
include_once "../../Classes/OutPutClass.php";
include_once "../../Classes/PersonClass.php";
include_once "../../Classes/ProductClass.php";
include_once "../../Classes/TypeClass.php";
include_once "../../Classes/UserClass.php";
include_once "../../Classes/CashPayment.php";
include_once "../../Classes/FawryPayment.php";
include_once "../../Classes/VisaPayment.php";